import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("landing", "routes/landing.tsx"),
  route("about", "routes/about.tsx"),
  route("courses", "routes/courses.tsx"),
  route("franchise", "routes/franchise.tsx"),
  route("contact", "routes/contact.tsx"),
  route("gallery", "routes/gallery.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("register", "routes/register.tsx"),
  route("teacher/login", "routes/teacher.login.tsx"),
  route("teacher/change-password", "routes/teacher.change-password.tsx"),
  route("teacher/forgot-password", "routes/teacher.forgot-password.tsx"),
  route("teacher/reset-password", "routes/teacher.reset-password.tsx"),
  route("admin/login", "routes/admin.login.tsx"),
  route("admin/forgot-password", "routes/admin.forgot-password.tsx"),
  route("admin/reset-password", "routes/admin.reset-password.tsx"),
  route("admin", "routes/admin/layout.tsx", [
    index("routes/admin.index.tsx"),
    route("dashboard", "routes/admin/dashboard.tsx"),
    route("users", "routes/admin/users.tsx"),
    route("payments", "routes/admin/payments.tsx"),
    route("teachers", "routes/admin/teachers.tsx"),
    route("courses", "routes/admin/courses.tsx"),
    route("materials", "routes/admin/materials.tsx"),
    route("tasks", "routes/admin/tasks.tsx"),
    route("planner", "routes/admin/planner.tsx"),
    route("books", "routes/admin/books.tsx"),
    route("inquiries", "routes/admin/inquiries.tsx"),
    route("reviews", "routes/admin/reviews.tsx"),
    route("gallery", "routes/admin/gallery.tsx"),
    route("settings", "routes/admin/settings.tsx"),
    route("notifications", "routes/admin/notifications.tsx"),
  ]),
  route("student", "routes/student/layout.tsx", [
    index("routes/student/index.tsx"),
    route("dashboard", "routes/student/dashboard.tsx"),
    route("library", "routes/student/library.tsx"),
    route("notifications", "routes/student/notifications.tsx"),
    route("settings", "routes/student/settings.tsx"),
  ]),
  route("student/checkout", "routes/student.checkout.tsx"),
  route("teacher/dashboard", "routes/teacher/dashboard.tsx"),
  route("teacher/tasks", "routes/teacher/tasks.tsx"),
  route("teacher/library", "routes/teacher/library.tsx"),
  route("teacher/planner", "routes/teacher/planner.tsx"),
  route("teacher/notifications", "routes/teacher/notifications.tsx"),
  route("teacher/settings", "routes/teacher/settings.tsx"),
] satisfies RouteConfig;
